// Shared components used across multiple sections
export { default as SectionHeader } from './SectionHeader';
export { default as BackgroundWrapper } from './BackgroundWrapper';
export { default as PhotoGallery } from './PhotoGallery';
export { default as PhotoGalleryProducts } from './PhotoGalleryProducts';
export { default as RichContent } from './RichContent';
export { default as SocialLinks } from './SocialLinks';
export { default as VideoEmbed } from './VideoEmbed';
export { default as VideoBlock } from './VideoBlock';
export { default as CallToAction } from './CallToAction';
export { default as Stats } from './Stats';
export { default as CTAStat } from './CTAStat';
export { default as EventsList } from './EventsList';
export { default as BusinessProfile } from './BusinessProfile';
export { default as SectionDivider } from './SectionDivider';
export { default as MediaItem } from './MediaItem';
export { default as HTMLContent } from './HTMLContent';
export { default as EmbeddableBusinessCard } from './EmbeddableBusinessCard';
export { default as SectionStrip } from './SectionStrip';