import { FoundingPro } from "./types";
import { Professional } from "@/lib/pages/for-professionals/types/professional";

// Real professionals data in complete Professional interface format
const realProfessionals: Omit<Professional, "id" | "yearsExperience">[] = [
  {
    name: "Melanie Marks",
    title: "Founder Of Glamlink",
    specialty: "Esthetician",
    location: "Henderson, NV",
    instagram: "@beautymarksvegas",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502709.jpg?alt=media&token=4101da30-796c-4d04-88eb-fbea6fbe1d6e",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491116_melanie_marks_min_cropped_4.5.jpg?alt=media&token=37ed4376-6cd2-4279-b57c-3823f424e7e3",
    isFounder: true,
    modalType: "standard",
    email: "melanie@glamlink.net",
    phone: "291-409-1041",
    website: "https://glamlink.net/",
    certificationLevel: "Bronze",
    bio: "Melanie Marks is a certified Esthetician professional with over 4 years of experience. Specializing in esthetician services, Melanie is dedicated to providing exceptional beauty and wellness services to clients in the Henderson, NV area. With a passion for the latest trends and techniques, they continuously expand skills to deliver outstanding results. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    description: undefined,
    salonName: "Glamlink",
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: true,
    rating: 0,
    reviewCount: 0,
    order: 1, // Founder always first
    createdAt: "2025-11-21T12:05:53.585Z",
    updatedAt: "November 25, 2025 at 5:47:31 PM UTC-8"
  },
  {
    name: "Marie Matteucci",
    title: "Esthetician",
    specialty: "Skincare Specialist",
    location: "Las Vegas, NV",
    instagram: "@mmmbeautysecrets",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502000.jpg?alt=media&token=marie_matteucci_123",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491000_melanie_marks_min_cropped_4.5.jpg?alt=media&token=marie_matteucci_456",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold",
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: 0,
    reviewCount: 0,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Tricia Evans",
    title: "Esthetician",
    specialty: "Waxing Specialist",
    location: "Las Vegas, NV",
    instagram: "@Prettykittywax",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502001.jpg?alt=media&token=tricia_evans_123",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491001_tricia_evans_min_cropped_4.5.jpg?alt=media&token=tricia_evans_456",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver",
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: 0,
    reviewCount: 0,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Glenn Gustafik",
    title: "Esthetician",
    specialty: "Skincare Expert",
    location: "Las Vegas, NV",
    instagram: "@glennemeryskincare",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502002.jpg?alt=media&token=glenn_gustafik_123",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491002_glenn_gustafik_min_cropped_4.5.jpg?alt=media&token=glenn_gustafik_456",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold",
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: 0,
    reviewCount: 0,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Trang Chen",
    title: "Nail Tech",
    specialty: "Nail Art & Design",
    location: "Las Vegas, NV",
    instagram: "@nailsbytee",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502003.jpg?alt=media&token=trang_chen_123",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491003_trang_chen_min_cropped_4.5.jpg?alt=media&token=trang_chen_456",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver",
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: 0,
    reviewCount: 0,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Kassandra Franco",
    title: "Medspa",
    specialty: "Medical Aesthetics",
    location: "Las Vegas, NV",
    instagram: "@snatchbykay",
    profileImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fcropped%2Fprofile_image_cropped_1764121502004.jpg?alt=media&token=kassandra_franco_123",
    portraitImage: "https://firebasestorage.googleapis.com/v0/b/glamlink-test.firebasestorage.app/o/admin%2Fprofile%2Fprofile_1764121491004_kassandra_franco_min_cropped_4.5.jpg?alt=media&token=kassandra_franco_456",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Platinum",
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: 0,
    reviewCount: 0,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Jackie Stryker",
    title: "Health & Wellness",
    specialty: "Body Reshaping",
    location: "Las Vegas, NV",
    instagram: "@reshapebodybar",
    profileImage: "/images/pros/jackie_stryker_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold", // Will be used in generateMockPros
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Jann Nguyen",
    title: "Esthetician",
    specialty: "Beauty Expert",
    location: "Las Vegas, NV",
    instagram: "@beautybyjann",
    profileImage: "/images/pros/jann_nguyen_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver", // Will be used in generateMockPros
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Christina Gorton",
    title: "Aesthetician",
    specialty: "Skincare Expert",
    location: "Redlands, CA",
    instagram: "@iconicaestheticbychristina",
    profileImage: "/images/pros/christina_gorton_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold", // Will be used in generateMockPros
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Polished Nails & Spa",
    title: "Nail Salon",
    specialty: "Nail Services",
    location: "Las Vegas, NV",
    instagram: "@polishednails",
    profileImage: "/images/pros/polished_nail_spa_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver", // Will be overridden in generateMockPros
        bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Vicky LePage",
    title: "Hair Stylist",
    specialty: "Hair Expert",
    location: "Las Vegas, NV",
    instagram: "@vickydoeshair",
    profileImage: "/images/pros/vicky_lepage_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold", // Will be overridden in generateMockPros
        bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Kate Sibley",
    title: "Hair Stylist",
    specialty: "Hair Expert",
    location: "Las Vegas, NV",
    instagram: "@katesue_bee",
    profileImage: "/images/pros/kate_sibley_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver", // Will be overridden in generateMockPros
        bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Teresa Hernandez",
    title: "Nurse Injector",
    specialty: "Injectables",
    location: "Las Vegas, NV",
    instagram: "@thernandez8",
    profileImage: "/images/pros/teresa_hernandez_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Platinum", // Will be overridden in generateMockPros
        bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Miguel Julio",
    title: "Makeup Artist",
    specialty: "Makeup & Beauty",
    location: "Las Vegas, NV",
    instagram: "@migueljuliobeauty",
    profileImage: "/images/pros/miguel_julio_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Gold", // Will be used in generateMockPros
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Parie Medical Spa",
    title: "Medical Spa",
    specialty: "Medical Aesthetics",
    location: "Las Vegas, NV",
    instagram: "@pariemedspa",
    profileImage: "/images/pros/parie_medical_spa_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Platinum", // Will be overridden in generateMockPros
        bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
  {
    name: "Carlee Kessler",
    title: "Esthetician",
    specialty: "Skincare Expert",
    location: "South Charleston, WV",
    instagram: "@sculptedbyskinalchemy",
    profileImage: "/images/pros/carlee_kessler_min_cropped_4.5.jpg",
    isFounder: false,
    modalType: "standard",
    email: undefined,
    phone: undefined,
    website: undefined,
    certificationLevel: "Silver", // Will be used in generateMockPros
    bio: undefined,
    description: undefined,
    salonName: undefined,
    salonAddress: undefined,
    bookingUrl: undefined,
    featured: false,
    rating: undefined,
    reviewCount: undefined,
    createdAt: undefined,
    updatedAt: undefined
  },
];

// Generate professionals based on feature flag
export const generateMockPros = (enablePagination: boolean = true): FoundingPro[] => {
  const certLevels: Array<"Bronze" | "Silver" | "Gold" | "Platinum"> = ["Bronze", "Silver", "Gold", "Platinum"];

  // When pagination is enabled: return all profiles for normal pagination (6 per page)
  // When pagination is disabled: return up to 12 profiles for continuous carousel
  const prosToReturn = enablePagination
    ? realProfessionals // All profiles for pagination
    : realProfessionals.slice(0, 12); // Max 12 for non-paginated carousel

  return prosToReturn.map((pro, i) => ({
    ...pro,
    id: (i + 1).toString(),
    certificationLevel: pro.certificationLevel || certLevels[i % certLevels.length],
    yearsExperience: ((i * 3) % 15) + 1,
    // Set featured for founders
    featured: pro.isFounder || false,
    // Set order based on professional data or index
    order: pro.order || (i + 1),
  }));
};

// Generate complete Professional data for admin use
export const generateCompleteMockPros = (enablePagination: boolean = true): Professional[] => {
  const certLevels: Array<"Bronze" | "Silver" | "Gold" | "Platinum"> = ["Bronze", "Silver", "Gold", "Platinum"];

  const prosToReturn = enablePagination
    ? realProfessionals // All profiles for pagination
    : realProfessionals.slice(0, 12); // Max 12 for non-paginated carousel

  return prosToReturn.map((pro, i) => ({
    id: (i + 1).toString(),
    ...pro,
    certificationLevel: certLevels[i % certLevels.length],
    yearsExperience: ((i * 3) % 15) + 1,
    featured: pro.isFounder || false,
    // Set order based on professional data or index
    order: pro.order || (i + 1),
    // Ensure image field compatibility (both profileImage and image)
    image: pro.profileImage,
    socialLinks: {
      instagram: pro.instagram || undefined,
    }
  }));
};
