export const samplePromosData = [
  {
    "descriptionShort": "Our latest cover in The Glamlink Edit, Parie Medical Spa, has teamed up with Glamlink to offer 1 winner a small area laser hair removal package.",
    "description": "<p>Our latest cover in The Glamlink Edit, the beautiful Parie Medical Spa has teamed up with Glamlink to offer 1 winner a small area laser hair removal package.</p>\n<h3 class=\"text-lg font-semibold text-gray-900 mb-2 mt-6\">How to enter:</h3>\n<ol class=\"list-decimal list-inside space-y-1 ml-4\">\n  <li>Download Glamink (user) or Glamlink Pro on the App Store. Sign up with code: <span class=\"font-semibold\">glampariemedspa</span></li>\n  <li>Follow <span class=\"font-semibold\">@pariemedspa</span> on Glamlink</li>\n  <li>Comment \"Parie\" on their post</li>\n</ol>\n<p class=\"mt-4\">Eligibility: 18+, must be a candidate for laser hair removal, no purchase necessary</p>\n\n<p class=\"mt-4\">Winner Announced Monday Nov 3</p>",
    "featured": true,
    "modalType": "standard",
    "priority": 10,
    "ctaText": "Enter Giveaway",
    "modalStatusBadge": "Sign Up Now",
    "discount": null,
    "visible": true,
    "customModalId": "",
    "modalContentHeader": "About This Offer",
    "popupDisplay": "Laser Hair Removal Giveaway",
    "modalCategoryBadge": "Giveaway",
    "image": "/images/free-laser-hair-removal.png",
    "category": "Giveaway Partnered with Parie Medical Spa",
    "id": "parie-laser-removal-giveaway",
    "title": "Laser Hair Removal Giveaway",
    "subtitle": "Parie Medical Spa",
    "link": "https://linktr.ee/glamlink_app",
    "startDate": "2025-10-07",
    "endDate": "2025-11-03",
    "createdAt": "2025-10-13T23:19:08.364Z",
    "updatedAt": "2025-11-21T09:30:46.339Z"
  },
  {
    "descriptionShort": "Vegas Beauty & Wellness Professionals - your app is here!  Glamlink helps clients find you by location, services and specialty.  Be among the first 100 to earn a Founders Badge.  Every month we will be picking one winner for $100 Amazon Gift Card.",
    "featured": true,
    "description": "<ol class=\"list-decimal list-inside space-y-1 ml-4\">\n  <li>Download Glamlink Pro on App Store</li>\n  <li>Add at least 1 post, clip, photo album</li>\n  <li>Set up your hours & services</li>\n  <li>Add in-app booking or your own booking link at <a href=\"http://www.crm.glamlink.net\" class=\"text-blue-600 hover:underline\">www.crm.glamlink.net</a></li>\n  <li>Share you joined Glamlink and tag <span class=\"font-semibold\">@glamlink_app</span> on IG</li>\n</ol>\n<p class=\"mt-4\">BONUS: Not only do you receive a Founders Badge but you can have the chance of being featured in our digital magazine, The Glamlink Edit.</p>\n<p class=\"mt-4\">Winner Announced Monday Nov 10</p>",
    "priority": 9,
    "ctaText": "Sign Up & Post",
    "modalStatusBadge": "Sign Up Now",
    "discount": null,
    "visible": true,
    "modalContentHeader": "How to enter",
    "popupDisplay": "$100 Gift Card Giveaway",
    "modalCategoryBadge": "Giveaway",
    "image": "/images/amazon_card_2.png",
    "category": "Gift Cards",
    "id": "amazon-gift-card-giveaway",
    "title": "$100 Amazon Gift Card Giveaway",
    "subtitle": "Gift Card",
    "link": "https://apps.apple.com/us/app/glamlink-pro/id6502331317",
    "startDate": "2025-10-13",
    "endDate": "2025-11-11",
    "createdAt": "2025-10-13T23:19:08.473Z",
    "updatedAt": "2025-10-13T23:19:08.473Z"
  },
  {
    "link": "https://apps.apple.com/us/app/glamlink-pro/id6502331317",
    "popupDisplay": "Thanksgiving Glam Giveaway",
    "modalType": "custom",
    "modalCategoryBadge": "Giveaway",
    "discount": null,
    "image": "/images/thanksgiving_glam.png",
    "subtitle": "Glam Makeover",
    "id": "mE1K3sx3qCO9OPLgek2H",
    "modalContentHeader": "How to Enter",
    "modalStatusBadge": "Download Now",
    "featured": true,
    "description": "<ol class=\"list-decimal list-inside space-y-1 ml-4\"> <li>Follow <strong>@glamlink_app</strong></li> <li>Follow <strong>@showoff_makeup</strong></li> <li>Like the giveaway post ❤️</li> <li>Tag your favorite beauty professional (limit 3 tags = 3 entries)</li> </ol> <p class=\"mt-4\">BONUS: Download <strong>Glamlink</strong> or <strong>Glamlink Pro</strong> for 3 extra entries.</p> <p class=\"mt-4\">Winner will be announced on Nov 26 on <strong>@glamlink_app</strong></p>",
    "descriptionShort": "Enter the Thanksgiving Glam Giveaway for a chance to win a free glam makeover with @showoff_makeup. Download the apps for bonus entries and follow the instructions to participate.",
    "title": "Thanksgiving Glam Giveaway",
    "visible": true,
    "ctaText": "Download & Enter",
    "category": "Giveaways",
    "customModalId": "thanksgiving-glam-giveaway",
    "priority": 9,
    "startDate": "2025-11-17",
    "endDate": "2025-11-25",
    "createdAt": "2025-11-19T06:14:26.937Z",
    "updatedAt": "2025-11-19T06:28:22.196Z"
  }
];