/**
 * Verification Config - Barrel exports
 */

export {
  STATUS_LABELS,
  STATUS_COLORS,
  STATUS_ICONS,
  BUSINESS_TYPE_OPTIONS,
  BUSINESS_TYPE_LABELS,
  VERIFICATION_STEPS,
  TOTAL_STEPS,
  DOCUMENT_TYPE_LABELS,
  ACCEPTED_ID_TYPES,
  DOCUMENT_UPLOAD_CONFIG,
  VERIFICATION_TERMS,
} from './statusConfig';
