'use client';

/**
 * DigitalPageCanvas - html2canvas Preview Display Component
 *
 * This component displays the preview generated by html2canvas, ensuring
 * what the user sees matches EXACTLY what the PDF will contain.
 *
 * Key features:
 * - Starts BLANK until user clicks "Generate" or "Generate Example"
 * - Displays html2canvas output (data URL) instead of React render
 * - Shows loading and error states
 * - Provides regenerate buttons after initial generation
 *
 * IMPORTANT: This does NOT render the preview React component directly.
 * The preview is generated off-screen by useCanvasPreview hook using
 * html2canvas, and the resulting image is displayed here.
 */

import React, { forwardRef, useMemo } from 'react';
import type { PagePdfSettings, PdfRatioType, DigitalPageType } from './types';
import type { CustomObject } from '@/lib/pages/admin/components/shared/editing/fields/custom/layout-objects';
import DigitalPreview from './preview/DigitalPreview';

// =============================================================================
// PDF DIMENSIONS
// =============================================================================

const DIMENSIONS: Record<Exclude<PdfRatioType, 'custom'>, { width: number; height: number }> = {
  'a4-portrait': { width: 210, height: 297 },
  'a4-landscape': { width: 297, height: 210 },
  '16:9': { width: 297, height: 167 },
  '4:3': { width: 280, height: 210 },
  'square': { width: 210, height: 210 },
};

// =============================================================================
// PROPS INTERFACE
// =============================================================================

interface DigitalPageCanvasProps {
  canvasDataUrl: string | null;
  pdfSettings: PagePdfSettings;
  scale?: number;
  showBorder?: boolean;
  className?: string;
  isGenerating?: boolean;
  progress?: string;
  error?: string | null;
  onGenerate: () => void;
  onGenerateExample: () => void;
  onSaveCanvas?: () => void;
  isSavingCanvas?: boolean;
  // Custom layout overlay props
  pageType?: DigitalPageType;
  objects?: CustomObject[];
}

// =============================================================================
// COMPONENT
// =============================================================================

const DigitalPageCanvas = forwardRef<HTMLDivElement, DigitalPageCanvasProps>(
  function DigitalPageCanvas(
    {
      canvasDataUrl,
      pdfSettings,
      scale = 1,
      showBorder = true,
      className = '',
      isGenerating = false,
      progress = '',
      error = null,
      onGenerate,
      onGenerateExample,
      onSaveCanvas,
      isSavingCanvas = false,
      pageType,
      objects,
    },
    ref
  ) {
    // Get dimensions based on PDF settings
    const dimensions = useMemo(() => {
      if (pdfSettings.ratio === 'custom') {
        return {
          width: pdfSettings.customWidth || 210,
          height: pdfSettings.customHeight || 297,
        };
      }
      return DIMENSIONS[pdfSettings.ratio] || DIMENSIONS['a4-portrait'];
    }, [pdfSettings.ratio, pdfSettings.customWidth, pdfSettings.customHeight]);

    // Calculate pixel dimensions for display
    const pixelDimensions = useMemo(() => {
      const dpi = 96;
      const baseWidth = (dimensions.width / 25.4) * dpi;
      const baseHeight = (dimensions.height / 25.4) * dpi;
      return {
        width: baseWidth * scale,
        height: baseHeight * scale,
      };
    }, [dimensions, scale]);

    return (
      <div className={`relative ${className}`}>
        {/* Dimension label */}
        <div className="absolute -top-6 left-0 text-xs text-gray-500">
          {dimensions.width}mm × {dimensions.height}mm
          {scale !== 1 && ` (${Math.round(scale * 100)}%)`}
        </div>

        {/* Canvas container */}
        <DigitalPreview
          ref={ref}
          canvasDataUrl={canvasDataUrl}
          backgroundColor={pdfSettings.backgroundColor || '#ffffff'}
          width={pixelDimensions.width}
          height={pixelDimensions.height}
          showBorder={showBorder}
          isGenerating={isGenerating}
          progress={progress}
          error={error}
          onGenerate={onGenerate}
          onGenerateExample={onGenerateExample}
          onSaveCanvas={onSaveCanvas}
          isSavingCanvas={isSavingCanvas}
          pageType={pageType}
          objects={objects}
        />

        {/* Ratio indicator */}
        <div className="absolute -bottom-6 right-0 text-xs text-gray-400">
          {pdfSettings.ratio === 'custom' ? 'Custom' : pdfSettings.ratio.toUpperCase()}
        </div>
      </div>
    );
  }
);

export default DigitalPageCanvas;
