/**
 * AI Configuration for AuthorBadge Content Block
 * Based on the component definition in content-discovery/maries-corner.ts
 */

export interface AuthorBadgeConfig {
  type: 'AuthorBadge';
  displayName: 'Author Badge';
  description: 'Author profile badge with customizable typography and layout';
  category: 'maries-corner';
  complexity: 'medium';
  fields: {
    authorName: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Author Name';
      description: 'Name of the article author';
    };
    authorTitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Author Title';
      description: 'Job title or role of the author';
    };
    authorImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Author Image';
      description: 'Profile photo of the author';
    };
    imageWidth: {
      aiEnabled: boolean;
      type: 'number';
      displayName: 'Image Width';
      description: 'Width of the author image in pixels';
    };
    imageHeight: {
      aiEnabled: boolean;
      type: 'number';
      displayName: 'Image Height';
      description: 'Height of the author image in pixels';
    };
    badgeText: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Badge Text';
      description: 'Text displayed on the author badge';
    };
    badgePosition: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Badge Position';
      description: 'Position of the badge relative to the image';
    };
    badgeFontSize: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Badge Font Size';
      description: 'Size of the badge text';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const authorBadgeConfig: AuthorBadgeConfig = {
  type: 'AuthorBadge',
  displayName: 'Author Badge',
  description: 'Author profile badge with customizable typography and layout',
  category: 'maries-corner',
  complexity: 'medium',
  fields: {
    authorName: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Author Name',
      description: 'Name of the article author'
    },
    authorTitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Author Title',
      description: 'Job title or role of the author'
    },
    authorImage: {
      aiEnabled: false, // Images not generated by AI
      type: 'image',
      displayName: 'Author Image',
      description: 'Profile photo of the author'
    },
    imageWidth: {
      aiEnabled: false, // Layout dimensions not typically AI-generated
      type: 'number',
      displayName: 'Image Width',
      description: 'Width of the author image in pixels'
    },
    imageHeight: {
      aiEnabled: false,
      type: 'number',
      displayName: 'Image Height',
      description: 'Height of the author image in pixels'
    },
    badgeText: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Badge Text',
      description: 'Text displayed on the author badge'
    },
    badgePosition: {
      aiEnabled: false, // UI layout not typically AI-generated
      type: 'select',
      displayName: 'Badge Position',
      description: 'Position of the badge relative to the image'
    },
    badgeFontSize: {
      aiEnabled: false,
      type: 'select',
      displayName: 'Badge Font Size',
      description: 'Size of the badge text'
    }
  },
  aiPrompts: {
    system: 'You are editing an author badge for a beauty magazine article. Focus on professional titles and badges that reflect expertise in the beauty industry.',
    examples: [
      'Update author information for a beauty professional',
      'Create professional title for magazine contributor',
      'Generate appropriate badge text for founding member',
      'Update author details for skincare expert'
    ]
  }
};