/**
 * AI Configuration for BeforeAfterImages Content Block
 * Based on the component definition in content-discovery/top-treatment.ts
 */

export interface BeforeAfterImagesConfig {
  type: 'BeforeAfterImages';
  displayName: 'Before/After Images';
  description: 'Media showcase with optional before/after comparison';
  category: 'top-treatment';
  complexity: 'high';
  fields: {
    heroImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Hero Image';
      description: 'Main display image for the treatment showcase';
    };
    'heroVideoSettings.videoType': {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Hero Video Type';
      description: 'Type of video source for hero section';
    };
    'heroVideoSettings.video': {
      aiEnabled: boolean;
      type: 'video';
      displayName: 'Hero Video File';
      description: 'Uploaded video file for hero section';
    };
    'heroVideoSettings.videoUrl': {
      aiEnabled: boolean;
      type: 'url';
      displayName: 'YouTube Video URL';
      description: 'YouTube video link for hero section';
    };
    beforeImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Before Image';
      description: 'Before treatment image';
    };
    afterImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'After Image';
      description: 'After treatment image showing results';
    };
    caption: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Media Caption';
      description: 'Caption for the images or video';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const beforeAfterImagesConfig: BeforeAfterImagesConfig = {
  type: 'BeforeAfterImages',
  displayName: 'Before/After Images',
  description: 'Media showcase with optional before/after comparison',
  category: 'top-treatment',
  complexity: 'high',
  fields: {
    heroImage: {
      aiEnabled: false, // Images not generated by AI
      type: 'image',
      displayName: 'Hero Image',
      description: 'Main display image for the treatment showcase'
    },
    'heroVideoSettings.videoType': {
      aiEnabled: false, // Technical settings not AI-generated
      type: 'select',
      displayName: 'Hero Video Type',
      description: 'Type of video source for hero section'
    },
    'heroVideoSettings.video': {
      aiEnabled: false, // Video files not generated by AI
      type: 'video',
      displayName: 'Hero Video File',
      description: 'Uploaded video file for hero section'
    },
    'heroVideoSettings.videoUrl': {
      aiEnabled: false, // Specific URLs not generated by AI
      type: 'url',
      displayName: 'YouTube Video URL',
      description: 'YouTube video link for hero section'
    },
    beforeImage: {
      aiEnabled: false,
      type: 'image',
      displayName: 'Before Image',
      description: 'Before treatment image'
    },
    afterImage: {
      aiEnabled: false,
      type: 'image',
      displayName: 'After Image',
      description: 'After treatment image showing results'
    },
    caption: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Media Caption',
      description: 'Caption for the images or video'
    }
  },
  aiPrompts: {
    system: 'You are creating captions for before/after beauty treatment showcases. Focus on describing the transformation, treatment details, and results in an engaging and professional manner.',
    examples: [
      'Write a caption highlighting dramatic skincare results',
      'Create a caption for facial treatment before/after photos',
      'Generate caption describing hair transformation results',
      'Add caption explaining makeup application technique'
    ]
  }
};