/**
 * AI Configuration for MariesPicks Content Block
 * Based on the component definition in content-discovery/maries-corner.ts
 */

export interface MariesPicksConfig {
  type: 'MariesPicks';
  displayName: 'Marie\'s Picks';
  description: 'Curated product recommendations';
  category: 'maries-corner';
  complexity: 'high';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Section Title';
      description: 'Title for the product recommendations section';
    };
    products: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Product Recommendations';
      description: 'Array of recommended products';
      itemFields: {
        name: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Product Name';
          description: 'Name of the recommended product';
        };
        category: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Product Category';
          description: 'Category or type of the product';
        };
        image: {
          aiEnabled: boolean;
          type: 'image';
          displayName: 'Product Image';
          description: 'Image of the recommended product';
        };
        link: {
          aiEnabled: boolean;
          type: 'link';
          displayName: 'Product Link';
          description: 'Link to the product page or purchase location';
        };
      };
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const mariesPicksConfig: MariesPicksConfig = {
  type: 'MariesPicks',
  displayName: 'Marie\'s Picks',
  description: 'Curated product recommendations',
  category: 'maries-corner',
  complexity: 'high',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Section Title',
      description: 'Title for the product recommendations section'
    },
    products: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Product Recommendations',
      description: 'Array of recommended products',
      itemFields: {
        name: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Product Name',
          description: 'Name of the recommended product'
        },
        category: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Product Category',
          description: 'Category or type of the product'
        },
        image: {
          aiEnabled: false, // Product images not generated by AI
          type: 'image',
          displayName: 'Product Image',
          description: 'Image of the recommended product'
        },
        link: {
          aiEnabled: false, // Specific product links not generated by AI
          type: 'link',
          displayName: 'Product Link',
          description: 'Link to the product page or purchase location'
        }
      }
    }
  },
  aiPrompts: {
    system: 'You are curating product recommendations for a beauty magazine. Focus on trending, high-quality products that would appeal to beauty professionals and enthusiasts. Consider seasonal trends and current beauty innovations.',
    examples: [
      'Add 4 trending skincare products for winter',
      'Update product recommendations for professional makeup artists',
      'Generate summer beauty picks with sun protection focus',
      'Create product recommendations for anti-aging skincare routine'
    ]
  }
};