/**
 * AI Configuration for NextIssuePreview Content Block
 * Based on the component definition in content-discovery/magazine-closing.ts
 */

export interface NextIssuePreviewConfig {
  type: 'NextIssuePreview';
  displayName: 'Next Issue Preview';
  description: 'Preview of upcoming magazine issue with highlights';
  category: 'magazine-closing';
  complexity: 'high';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Issue Title';
      description: 'Title of the next magazine issue';
    };
    date: {
      aiEnabled: boolean;
      type: 'date';
      displayName: 'Publication Date';
      description: 'When the next issue will be published';
    };
    description: {
      aiEnabled: boolean;
      type: 'html';
      displayName: 'Issue Description';
      description: 'Preview description of the upcoming issue';
    };
    coverImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Cover Image';
      description: 'Cover image for the next issue';
    };
    backgroundColor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Background Color';
      description: 'Background color for the preview section';
    };
    upcomingHighlightsTitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Highlights Section Title';
      description: 'Title for the upcoming highlights section';
    };
    upcomingHighlightsBackgroundColor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Highlights Background Color';
      description: 'Background color for highlight cards';
    };
    upcomingHighlights: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Upcoming Highlights';
      description: 'Featured content in the next issue';
      itemFields: {
        image: {
          aiEnabled: boolean;
          type: 'image';
          displayName: 'Highlight Image';
          description: 'Image representing the highlight';
        };
        title: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Highlight Title';
          description: 'Title of the featured content';
        };
        description: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Highlight Description';
          description: 'Brief description of the highlight';
        };
      };
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const nextIssuePreviewConfig: NextIssuePreviewConfig = {
  type: 'NextIssuePreview',
  displayName: 'Next Issue Preview',
  description: 'Preview of upcoming magazine issue with highlights',
  category: 'magazine-closing',
  complexity: 'high',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Issue Title',
      description: 'Title of the next magazine issue'
    },
    date: {
      aiEnabled: true,
      type: 'date',
      displayName: 'Publication Date',
      description: 'When the next issue will be published'
    },
    description: {
      aiEnabled: true,
      type: 'html',
      displayName: 'Issue Description',
      description: 'Preview description of the upcoming issue'
    },
    coverImage: {
      aiEnabled: false, // Cover images not generated by AI
      type: 'image',
      displayName: 'Cover Image',
      description: 'Cover image for the next issue'
    },
    backgroundColor: {
      aiEnabled: false, // Background styling not typically AI-generated
      type: 'text',
      displayName: 'Background Color',
      description: 'Background color for the preview section'
    },
    upcomingHighlightsTitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Highlights Section Title',
      description: 'Title for the upcoming highlights section'
    },
    upcomingHighlightsBackgroundColor: {
      aiEnabled: false,
      type: 'text',
      displayName: 'Highlights Background Color',
      description: 'Background color for highlight cards'
    },
    upcomingHighlights: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Upcoming Highlights',
      description: 'Featured content in the next issue',
      itemFields: {
        image: {
          aiEnabled: false, // Highlight images not generated by AI
          type: 'image',
          displayName: 'Highlight Image',
          description: 'Image representing the highlight'
        },
        title: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Highlight Title',
          description: 'Title of the featured content'
        },
        description: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Highlight Description',
          description: 'Brief description of the highlight'
        }
      }
    }
  },
  aiPrompts: {
    system: 'You are creating previews for upcoming beauty magazine content. Focus on exciting, compelling previews that will make readers anticipate the next issue. Include trending topics and seasonal beauty content.',
    examples: [
      'Generate preview for summer beauty issue with highlights',
      'Create next issue preview focusing on skincare innovations',
      'Add upcoming highlights for holiday makeup trends',
      'Generate preview content for spa and wellness issue'
    ]
  }
};