/**
 * AI Configuration for ProInsights Content Block
 * Based on the component definition in content-discovery/top-treatment.ts
 */

export interface ProInsightsConfig {
  type: 'ProInsights';
  displayName: 'Pro Insights';
  description: 'Professional insights and tips';
  category: 'top-treatment';
  complexity: 'high';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Section Title';
      description: 'Title for the professional insights section';
    };
    insights: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Professional Insights';
      description: 'Array of insights from beauty professionals';
      itemFields: {
        quote: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Professional Quote';
          description: 'The insight or tip from the professional';
        };
        author: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Professional Name';
          description: 'Name of the beauty professional';
        };
        title: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Professional Title';
          description: 'Title or specialization of the professional';
        };
        proImage: {
          aiEnabled: boolean;
          type: 'image';
          displayName: 'Professional Photo';
          description: 'Photo of the beauty professional';
        };
      };
    };
    backgroundColor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Background Color';
      description: 'Background color or gradient for the section';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const proInsightsConfig: ProInsightsConfig = {
  type: 'ProInsights',
  displayName: 'Pro Insights',
  description: 'Professional insights and tips',
  category: 'top-treatment',
  complexity: 'high',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Section Title',
      description: 'Title for the professional insights section'
    },
    insights: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Professional Insights',
      description: 'Array of insights from beauty professionals',
      itemFields: {
        quote: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Professional Quote',
          description: 'The insight or tip from the professional'
        },
        author: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Professional Name',
          description: 'Name of the beauty professional'
        },
        title: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Professional Title',
          description: 'Title or specialization of the professional'
        },
        proImage: {
          aiEnabled: false, // Professional photos not generated by AI
          type: 'image',
          displayName: 'Professional Photo',
          description: 'Photo of the beauty professional'
        }
      }
    },
    backgroundColor: {
      aiEnabled: false, // Background styling not typically AI-generated
      type: 'text',
      displayName: 'Background Color',
      description: 'Background color or gradient for the section'
    }
  },
  aiPrompts: {
    system: 'You are creating professional insights from beauty experts and industry professionals. Focus on valuable, actionable advice and expert knowledge about beauty treatments, techniques, and best practices.',
    examples: [
      'Generate expert insights about facial treatment techniques',
      'Create professional tips for skincare treatments',
      'Add dermatologist insights about anti-aging treatments',
      'Generate expert advice for hair care and styling'
    ]
  }
};