/**
 * AI Configuration for ProfessionalProfile Content Block
 * Based on the component definition in content-discovery/cover-pro-feature.ts
 */

export interface ProfessionalProfileConfig {
  type: 'ProfessionalProfile';
  displayName: 'Professional Profile';
  description: 'Featured professional hero section';
  category: 'cover-pro-feature';
  complexity: 'high';
  fields: {
    name: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Professional Name';
      description: 'Name of the featured professional';
    };
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Job Title';
      description: 'Professional title or role';
    };
    company: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Company Name';
      description: 'Company or business name';
    };
    quote: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Professional Quote';
      description: 'Inspirational quote or motto from the professional';
    };
    image: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Profile Image';
      description: 'Hero image of the professional';
    };
    useOverlay: {
      aiEnabled: boolean;
      type: 'checkbox';
      displayName: 'Use Gradient Overlay';
      description: 'Add gradient overlay for better text readability';
    };
    bio: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Biography';
      description: 'Professional biography and background';
    };
    location: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Location';
      description: 'City and state where the professional is based';
    };
    experience: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Experience';
      description: 'Years of experience in the field';
    };
    specialties: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Specialties';
      description: 'Areas of expertise and specialization';
      itemFields: {
        specialty: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Specialty';
          description: 'Individual area of expertise';
        };
      };
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const professionalProfileConfig: ProfessionalProfileConfig = {
  type: 'ProfessionalProfile',
  displayName: 'Professional Profile',
  description: 'Featured professional hero section',
  category: 'cover-pro-feature',
  complexity: 'high',
  fields: {
    name: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Professional Name',
      description: 'Name of the featured professional'
    },
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Job Title',
      description: 'Professional title or role'
    },
    company: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Company Name',
      description: 'Company or business name'
    },
    quote: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Professional Quote',
      description: 'Inspirational quote or motto from the professional'
    },
    image: {
      aiEnabled: false, // Professional photos not generated by AI
      type: 'image',
      displayName: 'Profile Image',
      description: 'Hero image of the professional'
    },
    useOverlay: {
      aiEnabled: false, // UI settings not typically AI-generated
      type: 'checkbox',
      displayName: 'Use Gradient Overlay',
      description: 'Add gradient overlay for better text readability'
    },
    bio: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Biography',
      description: 'Professional biography and background'
    },
    location: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Location',
      description: 'City and state where the professional is based'
    },
    experience: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Experience',
      description: 'Years of experience in the field'
    },
    specialties: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Specialties',
      description: 'Areas of expertise and specialization',
      itemFields: {
        specialty: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Specialty',
          description: 'Individual area of expertise'
        }
      }
    }
  },
  aiPrompts: {
    system: 'You are creating a comprehensive professional profile for a beauty industry expert. Focus on creating compelling, professional content that showcases expertise, experience, and credibility in the beauty field.',
    examples: [
      'Generate professional profile for makeup artist with 10 years experience',
      'Create bio and details for skincare specialist',
      'Update professional information for beauty entrepreneur',
      'Generate profile content for certified aesthetician'
    ]
  }
};