/**
 * AI Configuration for QuoteBlock Content Block
 * Based on the component definition in content-discovery/maries-corner.ts
 */

export interface QuoteBlockConfig {
  type: 'QuoteBlock';
  displayName: 'Quote Block';
  description: 'Featured quote or testimonial';
  category: 'maries-corner';
  complexity: 'medium';
  fields: {
    quote: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Quote Text';
      description: 'The main quote or testimonial text';
    };
    author: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Quote Author';
      description: 'Name of the person who said the quote';
    };
    authorTitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Author Title';
      description: 'Title, role, or credentials of the quote author';
    };
    backgroundImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Background Image';
      description: 'Optional background image for the quote block';
    };
    quoteStyle: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Quote Style';
      description: 'Visual style of the quote presentation';
    };
    quoteAlignment: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Quote Alignment';
      description: 'Text alignment for the quote';
    };
    quoteTextColor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Text Color';
      description: 'Color class for the quote text';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const quoteBlockConfig: QuoteBlockConfig = {
  type: 'QuoteBlock',
  displayName: 'Quote Block',
  description: 'Featured quote or testimonial',
  category: 'maries-corner',
  complexity: 'medium',
  fields: {
    quote: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Quote Text',
      description: 'The main quote or testimonial text'
    },
    author: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Quote Author',
      description: 'Name of the person who said the quote'
    },
    authorTitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Author Title',
      description: 'Title, role, or credentials of the quote author'
    },
    backgroundImage: {
      aiEnabled: false, // Background images not generated by AI
      type: 'image',
      displayName: 'Background Image',
      description: 'Optional background image for the quote block'
    },
    quoteStyle: {
      aiEnabled: false, // Visual styles not typically AI-generated
      type: 'select',
      displayName: 'Quote Style',
      description: 'Visual style of the quote presentation'
    },
    quoteAlignment: {
      aiEnabled: false,
      type: 'select',
      displayName: 'Quote Alignment',
      description: 'Text alignment for the quote'
    },
    quoteTextColor: {
      aiEnabled: false,
      type: 'text',
      displayName: 'Text Color',
      description: 'Color class for the quote text'
    }
  },
  aiPrompts: {
    system: 'You are creating inspirational and meaningful quotes for a beauty magazine. Focus on quotes that motivate, inspire, or provide wisdom related to beauty, self-care, and professional growth.',
    examples: [
      'Generate an inspirational quote about beauty and self-confidence',
      'Create a motivational quote for beauty entrepreneurs',
      'Add a professional quote about the beauty industry',
      'Generate a quote about self-care and wellness'
    ]
  }
};