/**
 * AI Configuration for SimilarProducts Content Block
 * Based on the component definition in content-discovery/top-product-spotlight.ts
 */

export interface SimilarProductsConfig {
  type: 'SimilarProducts';
  displayName: 'Similar Products';
  description: 'Grid of related products';
  category: 'top-product-spotlight';
  complexity: 'medium';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Section Title';
      description: 'Title for the similar products section';
    };
    products: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Similar Products';
      description: 'List of related or similar products';
      itemFields: {
        name: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Product Name';
          description: 'Name of the similar product';
        };
        price: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Product Price';
          description: 'Price of the similar product';
        };
        image: {
          aiEnabled: boolean;
          type: 'image';
          displayName: 'Product Image';
          description: 'Image of the similar product';
        };
        link: {
          aiEnabled: boolean;
          type: 'url';
          displayName: 'Product Link';
          description: 'URL to the product page';
        };
      };
    };
    backgroundColor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Background Color';
      description: 'Background color for the section';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const similarProductsConfig: SimilarProductsConfig = {
  type: 'SimilarProducts',
  displayName: 'Similar Products',
  description: 'Grid of related products',
  category: 'top-product-spotlight',
  complexity: 'medium',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Section Title',
      description: 'Title for the similar products section'
    },
    products: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Similar Products',
      description: 'List of related or similar products',
      itemFields: {
        name: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Product Name',
          description: 'Name of the similar product'
        },
        price: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Product Price',
          description: 'Price of the similar product'
        },
        image: {
          aiEnabled: false, // Product images not generated by AI
          type: 'image',
          displayName: 'Product Image',
          description: 'Image of the similar product'
        },
        link: {
          aiEnabled: false, // Specific product URLs not generated by AI
          type: 'url',
          displayName: 'Product Link',
          description: 'URL to the product page'
        }
      }
    },
    backgroundColor: {
      aiEnabled: false, // Background styling not typically AI-generated
      type: 'text',
      displayName: 'Background Color',
      description: 'Background color for the section'
    }
  },
  aiPrompts: {
    system: 'You are curating similar products for a beauty product spotlight. Focus on complementary products that would appeal to customers interested in the main featured product. Consider product categories, price ranges, and target demographics.',
    examples: [
      'Add 4 products similar to the featured anti-aging serum',
      'Generate complementary products for luxury foundation',
      'Create product recommendations in the same category',
      'Add similar products with competitive pricing'
    ]
  }
};