/**
 * AI Configuration for SocialFollow Content Block
 * Based on the component definition in content-discovery/maries-corner.ts
 */

export interface SocialFollowConfig {
  type: 'SocialFollow';
  displayName: 'Social Follow';
  description: 'Social media follow widget';
  category: 'maries-corner';
  complexity: 'low';
  fields: {
    'socialLink.platform': {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Platform';
      description: 'Social media platform';
    };
    'socialLink.handle': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Username/Handle';
      description: 'Social media username or handle';
    };
    'socialLink.followText': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Follow Text';
      description: 'Call-to-action text for following';
    };
    'socialLink.qrCode': {
      aiEnabled: boolean;
      type: 'url';
      displayName: 'QR Code URL';
      description: 'Profile URL for QR code generation';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const socialFollowConfig: SocialFollowConfig = {
  type: 'SocialFollow',
  displayName: 'Social Follow',
  description: 'Social media follow widget',
  category: 'maries-corner',
  complexity: 'low',
  fields: {
    'socialLink.platform': {
      aiEnabled: false, // Platform selection not typically AI-generated
      type: 'select',
      displayName: 'Platform',
      description: 'Social media platform'
    },
    'socialLink.handle': {
      aiEnabled: true,
      type: 'text',
      displayName: 'Username/Handle',
      description: 'Social media username or handle'
    },
    'socialLink.followText': {
      aiEnabled: true,
      type: 'text',
      displayName: 'Follow Text',
      description: 'Call-to-action text for following'
    },
    'socialLink.qrCode': {
      aiEnabled: false, // Specific URLs not generated by AI
      type: 'url',
      displayName: 'QR Code URL',
      description: 'Profile URL for QR code generation'
    }
  },
  aiPrompts: {
    system: 'You are creating social media follow prompts for a beauty magazine. Focus on engaging call-to-action text that encourages audience interaction and follows.',
    examples: [
      'Generate engaging follow text for Instagram',
      'Create call-to-action for social media engagement',
      'Update social handles for beauty brand',
      'Generate follow prompts for TikTok content'
    ]
  }
};