/**
 * AI Configuration for SpotlightReel Content Block
 * Based on the component definition in content-discovery/magazine-closing.ts
 */

export interface SpotlightReelConfig {
  type: 'SpotlightReel';
  displayName: 'Spotlight Reel';
  description: 'Grid of featured professionals with images and links';
  category: 'magazine-closing';
  complexity: 'high';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Reel Title';
      description: 'Main title for the spotlight reel';
    };
    subtitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Reel Subtitle';
      description: 'Subtitle or description for the reel';
    };
    gridLayout: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Grid Layout';
      description: 'Layout configuration for the grid';
    };
    spotlights: {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Spotlight Items';
      description: 'Featured professionals in the spotlight reel';
      itemFields: {
        name: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Professional Name';
          description: 'Name of the featured professional';
        };
        caption: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Caption';
          description: 'Brief description or title for the professional';
        };
        image: {
          aiEnabled: boolean;
          type: 'image';
          displayName: 'Professional Photo';
          description: 'Image of the featured professional';
        };
        link: {
          aiEnabled: boolean;
          type: 'link';
          displayName: 'Profile Link';
          description: 'Link to profile or modal content';
        };
      };
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const spotlightReelConfig: SpotlightReelConfig = {
  type: 'SpotlightReel',
  displayName: 'Spotlight Reel',
  description: 'Grid of featured professionals with images and links',
  category: 'magazine-closing',
  complexity: 'high',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Reel Title',
      description: 'Main title for the spotlight reel'
    },
    subtitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Reel Subtitle',
      description: 'Subtitle or description for the reel'
    },
    gridLayout: {
      aiEnabled: false, // Layout settings not typically AI-generated
      type: 'select',
      displayName: 'Grid Layout',
      description: 'Layout configuration for the grid'
    },
    spotlights: {
      aiEnabled: true,
      type: 'array',
      displayName: 'Spotlight Items',
      description: 'Featured professionals in the spotlight reel',
      itemFields: {
        name: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Professional Name',
          description: 'Name of the featured professional'
        },
        caption: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Caption',
          description: 'Brief description or title for the professional'
        },
        image: {
          aiEnabled: false, // Professional photos not generated by AI
          type: 'image',
          displayName: 'Professional Photo',
          description: 'Image of the featured professional'
        },
        link: {
          aiEnabled: false, // Specific links not generated by AI
          type: 'link',
          displayName: 'Profile Link',
          description: 'Link to profile or modal content'
        }
      }
    }
  },
  aiPrompts: {
    system: 'You are creating a spotlight reel featuring rising stars and notable professionals in the beauty industry. Focus on diverse, talented individuals who represent the future of beauty and showcase different specialties and backgrounds.',
    examples: [
      'Generate spotlight reel of 6 rising beauty professionals',
      'Create professional captions for beauty industry stars',
      'Add diverse beauty professionals to spotlight reel',
      'Generate titles and descriptions for featured beauty pros'
    ]
  }
};