/**
 * AI Configuration for StarProfile Content Block
 * Based on the component definition in content-discovery/rising-star.ts
 */

export interface StarProfileConfig {
  type: 'StarProfile';
  displayName: 'Star Profile';
  description: 'Featured star profile card';
  category: 'rising-star';
  complexity: 'high';
  fields: {
    starName: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Star Name';
      description: 'Name of the rising star';
    };
    starTitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Primary Title';
      description: 'Main title or role of the star';
    };
    starTitle2: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Secondary Title';
      description: 'Additional title or location information';
    };
    starImage: {
      aiEnabled: boolean;
      type: 'image';
      displayName: 'Star Photo';
      description: 'Profile image of the rising star';
    };
    quote: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Featured Quote';
      description: 'Inspirational or memorable quote from the star';
    };
    quoteAuthor: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Quote Attribution';
      description: 'Who said the quote (if different from star)';
    };
    quoteOverImage: {
      aiEnabled: boolean;
      type: 'checkbox';
      displayName: 'Quote Over Image';
      description: 'Display quote overlaid on the star image';
    };
    quoteBgClassName: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Quote Background';
      description: 'Background color for quote box';
    };
    bioTitle: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Bio Section Title';
      description: 'Title for the biography section';
    };
    bioTitleTag: {
      aiEnabled: boolean;
      type: 'select';
      displayName: 'Bio Title Tag';
      description: 'HTML heading tag for bio title';
    };
    bio: {
      aiEnabled: boolean;
      type: 'html';
      displayName: 'Biography';
      description: 'Detailed biography with rich text formatting';
    };
    bioBgClassName: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Bio Background';
      description: 'Background color for bio section';
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const starProfileConfig: StarProfileConfig = {
  type: 'StarProfile',
  displayName: 'Star Profile',
  description: 'Featured star profile card',
  category: 'rising-star',
  complexity: 'high',
  fields: {
    starName: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Star Name',
      description: 'Name of the rising star'
    },
    starTitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Primary Title',
      description: 'Main title or role of the star'
    },
    starTitle2: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Secondary Title',
      description: 'Additional title or location information'
    },
    starImage: {
      aiEnabled: false, // Profile photos not generated by AI
      type: 'image',
      displayName: 'Star Photo',
      description: 'Profile image of the rising star'
    },
    quote: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Featured Quote',
      description: 'Inspirational or memorable quote from the star'
    },
    quoteAuthor: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Quote Attribution',
      description: 'Who said the quote (if different from star)'
    },
    quoteOverImage: {
      aiEnabled: false, // UI layout options not typically AI-generated
      type: 'checkbox',
      displayName: 'Quote Over Image',
      description: 'Display quote overlaid on the star image'
    },
    quoteBgClassName: {
      aiEnabled: false, // Background styling not typically AI-generated
      type: 'text',
      displayName: 'Quote Background',
      description: 'Background color for quote box'
    },
    bioTitle: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Bio Section Title',
      description: 'Title for the biography section'
    },
    bioTitleTag: {
      aiEnabled: false, // HTML tags not typically AI-generated
      type: 'select',
      displayName: 'Bio Title Tag',
      description: 'HTML heading tag for bio title'
    },
    bio: {
      aiEnabled: true,
      type: 'html',
      displayName: 'Biography',
      description: 'Detailed biography with rich text formatting'
    },
    bioBgClassName: {
      aiEnabled: false, // Background styling not typically AI-generated
      type: 'text',
      displayName: 'Bio Background',
      description: 'Background color for bio section'
    }
  },
  aiPrompts: {
    system: 'You are creating a comprehensive profile for a rising star in the beauty industry. Focus on their journey, achievements, unique perspective, and what makes them stand out. Include inspiring quotes and engaging biographical content.',
    examples: [
      'Generate complete profile for a 25-year-old beauty entrepreneur',
      'Create bio and quote for rising makeup artist',
      'Add profile content for young skincare innovator',
      'Generate star profile for beauty influencer turned business owner'
    ]
  }
};