/**
 * AI Configuration for TipsList Content Block
 * Based on the component definition in content-discovery/whats-new-glamlink.ts
 */

export interface TipsListConfig {
  type: 'TipsList';
  displayName: 'Tips List';
  description: 'List of helpful tips and advice';
  category: 'whats-new-glamlink';
  complexity: 'medium';
  fields: {
    title: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Section Title';
      description: 'The main title for the tips section';
    };
    titleIcon: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Title Icon';
      description: 'Emoji or icon for the section title';
    };
    titleTag: {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Heading Tag';
      description: 'HTML heading tag (h1, h2, h3, etc.)';
    };
    'titleTypography.fontSize': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Font Size';
      description: 'CSS font size classes';
    };
    'titleTypography.fontFamily': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Font Family';
      description: 'CSS font family';
    };
    'titleTypography.fontWeight': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Font Weight';
      description: 'CSS font weight';
    };
    'titleTypography.color': {
      aiEnabled: boolean;
      type: 'text';
      displayName: 'Text Color';
      description: 'CSS text color classes';
    };
    'tips': {
      aiEnabled: boolean;
      type: 'array';
      displayName: 'Tips';
      description: 'Array of helpful tips';
      itemFields: {
        icon: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Icon';
          description: 'Emoji or icon for the tip';
        };
        title: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Tip Title';
          description: 'Headline or title for the tip';
        };
        description: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Description';
          description: 'Detailed explanation of the tip';
        };
        link: {
          aiEnabled: boolean;
          type: 'text';
          displayName: 'Link (Optional)';
          description: 'Optional URL for more information';
        };
      };
    };
  };
  aiPrompts: {
    system: string;
    examples: string[];
  };
}

export const tipsListConfig: TipsListConfig = {
  type: 'TipsList',
  displayName: 'Tips List',
  description: 'List of helpful tips and advice',
  category: 'whats-new-glamlink',
  complexity: 'medium',
  fields: {
    title: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Section Title',
      description: 'The main title for the tips section'
    },
    titleIcon: {
      aiEnabled: true,
      type: 'text',
      displayName: 'Title Icon',
      description: 'Emoji or icon for the section title'
    },
    titleTag: {
      aiEnabled: false, // Usually not changed by AI
      type: 'text',
      displayName: 'Heading Tag',
      description: 'HTML heading tag (h1, h2, h3, etc.)'
    },
    'titleTypography.fontSize': {
      aiEnabled: false, // Typography usually not changed by AI
      type: 'text',
      displayName: 'Font Size',
      description: 'CSS font size classes'
    },
    'titleTypography.fontFamily': {
      aiEnabled: false,
      type: 'text',
      displayName: 'Font Family',
      description: 'CSS font family'
    },
    'titleTypography.fontWeight': {
      aiEnabled: false,
      type: 'text',
      displayName: 'Font Weight',
      description: 'CSS font weight'
    },
    'titleTypography.color': {
      aiEnabled: false,
      type: 'text',
      displayName: 'Text Color',
      description: 'CSS text color classes'
    },
    'tips': {
      aiEnabled: true,
      type: 'array',
      displayName: 'Tips',
      description: 'Array of helpful tips',
      itemFields: {
        icon: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Icon',
          description: 'Emoji or icon for the tip'
        },
        title: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Tip Title',
          description: 'Headline or title for the tip'
        },
        description: {
          aiEnabled: true,
          type: 'text',
          displayName: 'Description',
          description: 'Detailed explanation of the tip'
        },
        link: {
          aiEnabled: false, // Usually specific URLs not generated by AI
          type: 'text',
          displayName: 'Link (Optional)',
          description: 'Optional URL for more information'
        }
      }
    }
  },
  aiPrompts: {
    system: 'You are editing a tips section for beauty professionals. Focus on practical, actionable advice that helps professionals succeed in their business and improve their skills.',
    examples: [
      'Add 3 professional tips for beauty entrepreneurs',
      'Update tip descriptions to be more actionable',
      'Create tips about social media and client engagement',
      'Add tips for building a successful beauty business'
    ]
  }
};